name: run-installer

on: [push]
jobs:
  install-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install zsh
        run: |
          sudo apt update
          sudo apt install zsh
      - name: Install dotfiles
        run: |
          ./install --email foo@acme.org --confirm-all-stages \
            --no-install-vscode-extensions
  install-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dotfiles
        run: |
          ./install --email foo@acme.org --confirm-all-stages \
            --no-install-vscode-extensions
